name: Ozonnell
favicon: null
layout_spectrum: 0.9800486122258008
typography_spectrum: 0.416127722710371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d0000'
    - '#f4bd01'
    - '#0c7489'
    - '#b576a1'
    - '#d9c2d2'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
